language: node_js

node_js: "lts/*"

os:
# - linux
  - osx

osx_image: xcode8

cache:
  directories: ./snapshot

script:
# Linux
#  - sudo dpkg --add-architecture i386
#  - sudo apt update
#  - curl -o steam.deb -L http://steamcdn-a.akamaihd.net/client/installer/steam.deb
#  - sudo apt -y install ./steam.deb
#  - xvfb-run --server-args="-screen 0 1024x768x24" steam &
#  - sleep 1m
#  - steam -shutdown
#
#
# Mac
  - npm i -g npm
#  - curl -o- -L https://yarnpkg.com/install.sh | bash
#  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
#  - yarn --version
  - curl -o ~/Desktop/Steam.dmg -L https://steamcdn-a.akamaihd.net/client/installer/steam.dmg
  - yes | hdiutil attach ~/Desktop/Steam.dmg &> /dev/null
  - cp -R /Volumes/Steam/Steam.app /Applications
  - hdiutil unmount /Volumes/Steam
  - /Applications/Steam.app/contents/MacOS/steam.sh -shutdown || echo "Exited with code $?"
  - sleep 10
  - sudo killall -9 steam || echo "Steam is not running"
  - /Applications/Steam.app/contents/MacOS/steam.sh -shutdown || echo "Exited with code $?"
  - sleep 10
  - sudo killall -9 steam || echo "Steam is not running"
  - /Applications/Steam.app/contents/MacOS/steam.sh -login $stu $stp -shutdown || echo "Exited with code $?"
  - sleep 10
  - sudo killall -9 steam || echo "Steam is not running"
  - ls -a ~/Library/Application\ Support/Steam
#  - yarn test ~/Library/Application\ Support/Steam
  - node tests/test.js ~/Library/Application\ Support/Steam

after_success:

notifications:
  email: false
