language: node_js

node_js: "lts/*"

os:
  - linux
#  - osx

cache:
  yarn: true

script:
  - sudo dpkg --add-architecture i386
  - sudo apt update
  - curl -o steam.deb -L http://steamcdn-a.akamaihd.net/client/installer/steam.deb
  - sudo apt -y install ./steam.deb
  - xvfb-run --server-args="-screen 0 1024x768x24" steam &
  - sleep 1m
  - steam -shutdown

after_success:

notifications:
  email: false
