language: node_js

node_js: "lts/*"

os: osx

script:
  - npm i -g npm
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin"
  - chmod u+x ./ci_install.sh
  - ./ci_install.sh
  - echo "Taking snapshot of Steam folder..."
  - node ./src/cli.js -kqs -t ~/Library/Application\ Support/Steam -e Steam.AppBundle -e logs -e music -e htmlcache -e widevine > ~/Desktop/snapshot.json
  - cat ~/Desktop/snapshot.json

notifications:
  email: false
  