language: node_js

node_js: "lts/*"

os:
# - linux
  - osx

osx_image: xcode8

cache:
  directories:
    - ~/Library/Application\ Support/Steam
    - ~/Desktop/snapshots

script:
# Linux
#  - sudo dpkg --add-architecture i386
#  - sudo apt update
#  - curl -o steam.deb -L http://steamcdn-a.akamaihd.net/client/installer/steam.deb
#  - sudo apt -y install ./steam.deb
#  - xvfb-run --server-args="-screen 0 1024x768x24" steam &
#  - sleep 1m
#  - steam -shutdown
#
#
# Mac
  - npm i -g npm
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin"
  - echo "travis_fold:start:ci_install"
  - chmod u+x ./ci_install.sh
  - ./ci_install.sh
  - echo "travis_fold:end:ci_install"
  - echo "travis_fold:start:snapshot"
  - echo "Taking snapshot of Steam folder..."
  - yarn test ~/Library/Application\ Support/Steam false false false false '' '' 5 ~/Desktop
  - echo "travis_fold:end:snapshot"

after_success:
  - cat ~/Desktop/snapshot.json

notifications:
  email: false
