# Build with NodeJS v# using architecture-specific instalallations
environment:
  yarn_version: '1.9.4'

# Build using both 32-bit and 64-bit Windows.
platform:
  - x64

# Because of this:
#   https://help.github.com/articles/dealing-with-line-endings/
init:
  - git config --global core.autocrlf input

install:
  - ps: Write-Host "Installing Steam..."
  - ps: (New-Object Net.WebClient).DownloadFile("http://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe", "$env:temp\SteamSetup.exe")
  - ps: Start-Process -FilePath $env:temp\SteamSetup.exe -ArgumentList /S -Wait -PassThru
  - ps: Start-Process -FilePath "C:\\Program Files (x86)\\Steam\\Steam.exe" -ArgumentList @("-login", $env:steamu, $env:steamp) -PassThru -WindowStyle Hidden
  - ps: Start-Sleep -s 240
  - ps: Start-Process -FilePath "C:\\Program Files (x86)\\Steam\\Steam.exe" -ArgumentList "-shutdown" -Wait -PassThru -WindowStyle Hidden
  - dir "C:\Program Files (x86)\Steam"
  - dir "C:\Program Files (x86)\Steam\config"

# Quiet-ish build.
build:
  verbosity: minimal


# Run build (tests)
build_script:
  - echo "Hi"
