# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Steam on CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-10.15 # 10.15, 12

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        stu: ${{secrets.STU}}
        stp: ${{secrets.STP}}
    - run: ls -ah
    - run: chmod u+x ./ci_install.sh
    - run: ./ci_install.sh
    - run: echo "Taking snapshot of Steam folder..."
    - run: node ./src/cli.js -kqs -t ~/Library/Application\ Support/Steam -e Steam.AppBundle -e logs -e music -e htmlcache -e widevine > ~/Desktop/snapshot.json
    - run: cat ~/Desktop/snapshot.json
